services:
  mysql:
    container_name: case-board-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql # Map the MySQL data to a folder on the host machine
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - case-board-network

  backend:
    container_name: case-board
    image: oscarhkli/case-board
    platform: linux/amd64
    ports:
      - "61001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    env_file:
      - .env # Load variables from .env file
    networks:
      - case-board-network

  frontend:
    container_name: react-case-board
    image: oscarhkli/react-case-board
    platform: linux/amd64
    ports:
      - "8080:80"
    networks:
      - case-board-network

volumes:
  mysql-data:

networks:
  case-board-network:
    driver: bridge