spring:
  application:
    name: case-board

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://case-board-mysql:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  include-application-name: false
  pattern:
    correlation: ""
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"

---
spring:
  config:
    activate:
      on-profile: default

server:
  port: 61001

---
spring:
  config:
    activate:
      on-profile: cloud

server:
  port: 8080
