create table cases (
    id bigint generated by default as identity,
    case_number varchar(255) unique not null,
    title varchar(255) not null,
    description text,
    status varchar(255) not null,
    created_datetime timestamp,
    last_modified_datetime timestamp,
    primary key (id)
);

create index idx_cases_id on cases(id);